---
- hosts: all

  become: true

  tasks:
    - name: APT Package Updater
      ansible.builtin.apt:
        name: "*"
        state: latest
      
      
#      apt:
#        upgrade: yes
#        update_cache: yes
