---
- hosts: all

  become: true

  tasks:
    - name: APT Package Updater
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
      
      
#      apt:
#        upgrade: yes
#        update_cache: yes
